FROM centos:latest
### DOPR START, code until tag `DOPR END` was auto-generated by dopr service

RUN yum install -y dnf dnf-plugins-core \
    && mkdir -p /etc/yum.repos.d/
RUN dnf copr enable -y lnykryn/systemd
### DOPR END

### DOPR START, code until tag `DOPR END` was auto-generated by dopr service
RUN yum install -y dnf dnf-plugins-core \
&& mkdir -p /etc/yum.repos.d/
RUN dnf copr enable -y lnykryn/systemd
### DOPR END
RUN yum -y update systemd
VOLUME ["/run", "/tmp"]
ENV container docker
VOLUME /sys/fs/cgroup
CMD /usr/sbin/init
